### PR TITLE
cleaning up fronting a little bit

### PR DESCRIPTION
**Pull request by myleshorton**

### CODE REVIEW

**Comment by myleshorton** [comment]
This just uses the new, arguably slightly cleaner method for configuring fronting and fixed compile errors in the test (although the test still fails).

**Comment by atavism** [comment]
Your changes look good to me, @myleshorton. I noticed the `TestCheckUpdateAvailable` test just hangs for me though. Are you seeing something similar?

**Comment by atavism** [comment]
It looks like the certificate issued for `update-stage.getlantern.org` expired last August. I don't have access to the machine that's on. Maybe try renewing it to see if that fixes the issue?

**Comment by atavism** [comment]
@myleshorton We can just merge this for now and take care of that later?

**Comment by joesis** [comment]
@myleshorton @atavism the cert is renewed and a crontab is installed to renew in weekly basis.

**Comment by atavism** [comment]
Awesome, thanks @joesis!!

**Comment by myleshorton** [comment]
Hey sorry for the slow reply -- thanks guys!

**Pull request merged**
